### ISSUE TITLE
Store Posts (XML) in Blob storage?

### ISSUE THREAD

**Issue by pedropaf** [madskristensen/MiniBlog#109]
Hi, thanks for this great blog. I'm trying to host this as a Virtual Application in Azure Cloud Services. It's working, but when I redeploy, I'd need to download the posts from the server to not lose them. Which is not very handy if I redeploy often. Does the blog support storing the posts in a DB / Azure Blob Storage? That way I could redeploy without worrying about the content.

Thanks,

**Comment by aarondcoleman** [comment]
@Gordon-Beeming did you end up implementing this or find someone else who had?

**Comment by Gordon-Beeming** [comment]
Sorry, haven't done this yet. Will take a look tonight and see. Shouldn't be hard to do. Check back tomorrow :) @aarondcoleman

**Comment by Gordon-Beeming** [comment]
Hi @aarondcoleman. Take at the branch AzureBlobStorage in my fork of MiniBlog. It saves your posts to blog storage instead of posts folder https://github.com/Gordon-Beeming/MiniBlog/tree/AzureBlobStorage

**Comment by aarondcoleman** [comment]
Hi @Gordon-Beeming -- thanks checking that in! Very helpful. You might want to regenerate that Azure key if you haven't done so already because it's checked in, in-line.

**Comment by aarondcoleman** [comment]
@madskristensen I can appreciate the intent to keep Miniblog totally simple and streamlined. That said, might there be an interest in a way to restructure Storage.cs where someone could essentially override, implement an interface, or something outside the scope of a file system?

My ideal would be to personally keep a fork of this with say, Azure blob, but I could rebase to master and keep up with the new features that make it in to the project.

**Comment by Gordon-Beeming** [comment]
I'm fine with my site running out the file system for now. Made this because it wasaasked for :-)

Deleted that storage account after checking inot.

Sent by Outlook<http://taps.io/outlookmobile> for Android



On Thu, Feb 26, 2015 at 8:18 AM -0800, "Aaron Coleman" <notifications@github.com<mailto:notifications@github.com>> wrote:


@Gordon-Beeming<https://github.com/Gordon-Beeming> did you end up implementing this or find someone else who had?

-
